version: '3.4'

services:
  #consul:
  #  image: consul
  #  container_name: consul
  #  ports:
  #    - "8500:8500"
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "81:80"
    environment:
     - GlobalConfiguration__ServiceDiscoveryProvider__Host=consul
     - GlobalConfiguration__ServiceDiscoveryProvider__Port=8500
  serviceapi:
    image: jeffaries/serviceapi
    build:
      context: .
      dockerfile: ServiceApi/Dockerfile
    ports:
      - "82:80"
    environment:
     - InstanceName=apiInstance82
     - Service__IP=serviceapi
     - Service__Port=82
     - consul__serviceUrl=http://consul:8500
 


